// Official 2026 offseason additions and retention moves.
// Source snapshot: NBA.com all-30-team offseason tracker, updated September 16, 2026.
const offseasonMoves = [
  ['Atlanta Hawks','atl','Jock Landale','Re-signing','Returns on a 1-year deal'],
  ['Atlanta Hawks','atl','CJ McCollum','Re-signing','Returns on a 1-year deal'],
  ['Atlanta Hawks','atl','Luguentz Dort','Trade','Acquired from Oklahoma City'],
  ['Atlanta Hawks','atl','Ryan Nembhard','Trade','Acquired from Dallas'],
  ['Atlanta Hawks','atl','Aaron Wiggins','Trade','Acquired from Oklahoma City'],
  ['Boston Celtics','bos','Ron Harper Jr.','Re-signing','Returns on a 3-year deal'],
  ['Boston Celtics','bos','Neemias Queta','Re-signing','Returns on a 4-year deal'],
  ['Boston Celtics','bos','Jordan Walsh','Re-signing','Signs a 3-year extension'],
  ['Boston Celtics','bos','Mike Conley','Signing','Signs a 1-year deal'],
  ['Boston Celtics','bos','Paul George','Trade','Acquired from Philadelphia'],
  ['Boston Celtics','bos','Mitchell Robinson','Signing','Signs a 3-year deal'],
  ['Brooklyn Nets','bkn','Josh Minott','Re-signing','Returns on a 2-year deal'],
  ['Brooklyn Nets','bkn','Day’Ron Sharpe','Re-signing','Returns on a 2-year deal'],
  ['Brooklyn Nets','bkn','Keon Ellis','Signing','Signs a 2-year deal'],
  ['Brooklyn Nets','bkn','Julius Randle','Trade','Acquired from Minnesota in a 4-team deal'],
  ['Brooklyn Nets','bkn','Moritz Wagner','Signing','Signs a 2-year deal'],
  ['Charlotte Hornets','cha','Coby White','Re-signing','Returns on a 3-year deal'],
  ['Charlotte Hornets','cha','Grayson Allen','Trade','Acquired from Phoenix'],
  ['Charlotte Hornets','cha','Dorian Finney-Smith','Trade','Acquired from Houston'],
  ['Charlotte Hornets','cha','Royce O’Neale','Trade','Acquired from Phoenix'],
  ['Charlotte Hornets','cha','Naz Reid','Trade','Acquired from Minnesota in a 4-team deal'],
  ['Charlotte Hornets','cha','Dennis Schröder','Trade','Acquired from Cleveland in a 5-team deal'],
  ['Chicago Bulls','chi','Zach Collins','Re-signing','Returns on a 2-year deal'],
  ['Chicago Bulls','chi','Nic Claxton','Trade','Acquired from Brooklyn in a 4-team deal'],
  ['Chicago Bulls','chi','Norman Powell','Signing','Signs a 2-year deal'],
  ['Cleveland Cavaliers','cle','Thomas Bryant','Re-signing','Returns on a 1-year deal'],
  ['Cleveland Cavaliers','cle','James Harden','Re-signing','Returns on a 3-year deal'],
  ['Cleveland Cavaliers','cle','Donovan Mitchell','Re-signing','Signs a 4-year extension'],
  ['Cleveland Cavaliers','cle','Khalifa Diop','Signing','Signs a 4-year deal'],
  ['Cleveland Cavaliers','cle','Mario Hezonja','Signing','Signs a 1-year deal'],
  ['Cleveland Cavaliers','cle','Peyton Watson','Trade','Acquired from Denver in a 5-team sign-and-trade'],
  ['Dallas Mavericks','dal','Moussa Cissé','Re-signing','Returns on a 2-year deal'],
  ['Dallas Mavericks','dal','Naji Marshall','Re-signing','Signs a 3-year extension'],
  ['Dallas Mavericks','dal','Santi Aldama','Trade','Acquired from Memphis'],
  ['Dallas Mavericks','dal','Tarik Biberović','Signing','Signs a 2-year deal'],
  ['Dallas Mavericks','dal','Zaccharie Risacher','Trade','Acquired from Atlanta'],
  ['Dallas Mavericks','dal','Marcus Sasser','Trade','Acquired from Detroit'],
  ['Denver Nuggets','den','Tyus Jones','Re-signing','Returns on a 1-year deal'],
  ['Denver Nuggets','den','Spencer Jones','Re-signing','Returns on a 2-year deal'],
  ['Denver Nuggets','den','Marvin Bagley III','Signing','Signs a 1-year deal'],
  ['Denver Nuggets','den','DeMar DeRozan','Signing','Signs a 1-year deal'],
  ['Denver Nuggets','den','Alpha Diallo','Signing','Signs a 1-year deal'],
  ['Detroit Pistons','det','Javonte Green','Re-signing','Returns on a 1-year deal'],
  ['Detroit Pistons','det','Kevin Huerter','Re-signing','Returns on a 3-year deal'],
  ['Detroit Pistons','det','John Collins','Trade','Acquired from the Clippers in a sign-and-trade'],
  ['Detroit Pistons','det','Gary Harris','Trade','Acquired from Milwaukee'],
  ['Detroit Pistons','det','Isaiah Joe','Trade','Acquired from Oklahoma City'],
  ['Detroit Pistons','det','Taurean Prince','Trade','Acquired from Milwaukee'],
  ['Golden State Warriors','gsw','Charles Bassey','Re-signing','Returns on a 1-year deal'],
  ['Golden State Warriors','gsw','Draymond Green','Re-signing','Returns on a 1-year deal'],
  ['Golden State Warriors','gsw','Al Horford','Re-signing','Returns on a 2-year deal'],
  ['Golden State Warriors','gsw','De’Anthony Melton','Re-signing','Returns on a 2-year deal'],
  ['Golden State Warriors','gsw','Gary Payton II','Re-signing','Returns on a 1-year deal'],
  ['Golden State Warriors','gsw','Kristaps Porziņģis','Re-signing','Returns on a 2-year deal'],
  ['Golden State Warriors','gsw','Georges Niang','Signing','Signs a 1-year deal'],
  ['Golden State Warriors','gsw','Brandon Williams','Signing','Signs a 1-year deal'],
  ['Houston Rockets','hou','Isaiah Crawford','Re-signing','Returns on a 4-year deal'],
  ['Houston Rockets','hou','Tari Eason','Re-signing','Returns on a 5-year deal'],
  ['Houston Rockets','hou','Jae’Sean Tate','Re-signing','Returns on a 1-year deal'],
  ['Houston Rockets','hou','Amen Thompson','Re-signing','Signs a 5-year extension'],
  ['Houston Rockets','hou','Bogdan Bogdanović','Signing','Signs a 1-year deal'],
  ['Houston Rockets','hou','Marcus Smart','Signing','Signs a 2-year deal'],
  ['Indiana Pacers','ind','Larry Nance Jr.','Signing','Signs a 1-year deal'],
  ['Indiana Pacers','ind','Kelly Oubre Jr.','Signing','Signs a 2-year deal'],
  ['LA Clippers','lac','Bradley Beal','Re-signing','Returns on a 2-year deal'],
  ['LA Clippers','lac','Jordan Miller','Re-signing','Returns on a 3-year deal'],
  ['LA Clippers','lac','Kobe Sanders','Re-signing','Returns on a 4-year deal'],
  ['LA Clippers','lac','Johni Broome','Trade','Acquired from Philadelphia'],
  ['LA Clippers','lac','Gradey Dick','Trade','Acquired from Toronto'],
  ['LA Clippers','lac','Rui Hachimura','Signing','Signs a 2-year deal'],
  ['LA Clippers','lac','Brandon Ingram','Trade','Acquired from Toronto'],
  ['LA Clippers','lac','Max Strus','Trade','Acquired from Cleveland in a 5-team deal'],
  ['Los Angeles Lakers','lal','Austin Reaves','Re-signing','Returns on a 4-year deal'],
  ['Los Angeles Lakers','lal','Quentin Grimes','Signing','Signs a 4-year deal'],
  ['Los Angeles Lakers','lal','Jaden Hardy','Trade','Acquired from Washington'],
  ['Los Angeles Lakers','lal','Walker Kessler','Trade','Acquired from Utah in a sign-and-trade'],
  ['Los Angeles Lakers','lal','Kevon Looney','Signing','Signs a 1-year deal'],
  ['Los Angeles Lakers','lal','Sandro Mamukelashvili','Signing','Signs a 4-year deal'],
  ['Los Angeles Lakers','lal','Collin Sexton','Signing','Signs a 2-year deal'],
  ['Los Angeles Lakers','lal','Matisse Thybulle','Signing','Signs a 1-year deal'],
  ['Los Angeles Lakers','lal','Ziaire Williams','Signing','Signs a 1-year deal'],
  ['Memphis Grizzlies','mem','Jerami Grant','Trade','Acquired from Portland'],
  ['Memphis Grizzlies','mem','Jordan Hawkins','Trade','Acquired from New Orleans'],
  ['Memphis Grizzlies','mem','Kris Murray','Trade','Acquired from Portland'],
  ['Memphis Grizzlies','mem','Micah Peavy','Trade','Acquired from New Orleans'],
  ['Memphis Grizzlies','mem','Quinten Post','Signing','Signs a 3-year deal'],
  ['Memphis Grizzlies','mem','D’Angelo Russell','Trade','Acquired from Washington'],
  ['Memphis Grizzlies','mem','Isaiah Stewart','Trade','Acquired from Detroit'],
  ['Miami Heat','mia','Simone Fontecchio','Re-signing','Returns on a 1-year deal'],
  ['Miami Heat','mia','Andrew Wiggins','Re-signing','Returns on a 3-year deal'],
  ['Miami Heat','mia','Giannis Antetokounmpo','Trade','Acquired from Milwaukee'],
  ['Miami Heat','mia','Tim Hardaway Jr.','Signing','Signs a 1-year deal'],
  ['Miami Heat','mia','Bobby Portis','Trade','Acquired from Milwaukee'],
  ['Miami Heat','mia','Nick Richards','Signing','Signs a 1-year deal'],
  ['Miami Heat','mia','Klay Thompson','Signing','Signs a 2-year deal'],
  ['Milwaukee Bucks','mil','Ousmane Dieng','Re-signing','Returns on a 3-year deal'],
  ['Milwaukee Bucks','mil','Bogoljub Marković','Re-signing','Returns on a multi-year deal'],
  ['Milwaukee Bucks','mil','Pete Nance','Re-signing','Returns on a 2-year deal'],
  ['Milwaukee Bucks','mil','Gary Trent Jr.','Re-signing','Returns on a 4-year deal'],
  ['Milwaukee Bucks','mil','Tyler Herro','Trade','Acquired from Miami'],
  ['Milwaukee Bucks','mil','Kasparas Jakučionis','Trade','Acquired from Miami'],
  ['Milwaukee Bucks','mil','Jaime Jaquez Jr.','Trade','Acquired from Miami'],
  ['Milwaukee Bucks','mil','Kel’el Ware','Trade','Acquired from Miami'],
  ['Milwaukee Bucks','mil','Caris LeVert','Trade','Acquired from Detroit'],
  ['Minnesota Timberwolves','min','Jaylen Clark','Re-signing','Re-signs with Minnesota'],
  ['Minnesota Timberwolves','min','Ayo Dosunmu','Re-signing','Returns on a 4-year deal'],
  ['Minnesota Timberwolves','min','Bones Hyland','Re-signing','Re-signs with Minnesota'],
  ['Minnesota Timberwolves','min','LaMelo Ball','Trade','Acquired from Charlotte in a 4-team deal'],
  ['Minnesota Timberwolves','min','Jonathan Kuminga','Signing','Signs a 2-year deal'],
  ['Minnesota Timberwolves','min','Trey Lyles','Signing','Signs a 1-year deal'],
  ['Minnesota Timberwolves','min','Cody Williams','Trade','Acquired from Utah'],
  ['New Orleans Pelicans','nop','DeAndre Jordan','Re-signing','Returns on a 1-year deal'],
  ['New Orleans Pelicans','nop','AJ Johnson','Trade','Acquired from Memphis'],
  ['New Orleans Pelicans','nop','Bennedict Mathurin','Signing','Signs a 2-year deal'],
  ['New Orleans Pelicans','nop','Trendon Watford','Signing','Signs a 1-year deal'],
  ['New York Knicks','nyk','Jose Alvarado','Re-signing','Returns on a 3-year deal'],
  ['New York Knicks','nyk','Jordan Clarkson','Re-signing','Returns on a 1-year deal'],
  ['New York Knicks','nyk','Mohamed Diawara','Re-signing','Returns on a multi-year deal'],
  ['New York Knicks','nyk','Landry Shamet','Re-signing','Returns on a 4-year deal'],
  ['New York Knicks','nyk','Andre Drummond','Signing','Signs a 1-year deal'],
  ['New York Knicks','nyk','John Konchar','Signing','Reported 1-year addition'],
  ['Oklahoma City Thunder','okc','Isaiah Hartenstein','Re-signing','Returns on a 3-year deal'],
  ['Oklahoma City Thunder','okc','Kenrich Williams','Re-signing','Returns on a 1-year deal'],
  ['Orlando Magic','orl','Jevon Carter','Re-signing','Returns on a 1-year deal'],
  ['Orlando Magic','orl','Jonathan Isaac','Re-signing','Returns on a 1-year deal'],
  ['Orlando Magic','orl','Nikola Vučević','Signing','Signs a 1-year deal'],
  ['Philadelphia 76ers','phi','Jaylen Brown','Trade','Acquired from Boston'],
  ['Philadelphia 76ers','phi','Kentavious Caldwell-Pope','Signing','Signs a 1-year deal'],
  ['Philadelphia 76ers','phi','Ariel Hukporti','Signing','Signs a 1-year deal'],
  ['Philadelphia 76ers','phi','LeBron James','Signing','Signs a 2-year deal'],
  ['Philadelphia 76ers','phi','Anfernee Simons','Signing','Signs a 2-year deal'],
  ['Philadelphia 76ers','phi','Dean Wade','Signing','Signs a 4-year deal'],
  ['Phoenix Suns','phx','Dillon Brooks','Re-signing','Signs a 3-year extension'],
  ['Phoenix Suns','phx','Collin Gillespie','Re-signing','Returns on a 4-year deal'],
  ['Phoenix Suns','phx','Jordan Goodwin','Re-signing','Returns on a 3-year deal'],
  ['Phoenix Suns','phx','Haywood Highsmith','Re-signing','Returns on a 1-year deal'],
  ['Phoenix Suns','phx','Mark Williams','Re-signing','Returns on a 3-year deal'],
  ['Phoenix Suns','phx','Miles Bridges','Trade','Acquired from Charlotte'],
  ['Phoenix Suns','phx','Luke Kennard','Signing','Signs a 2-year deal'],
  ['Portland Trail Blazers','por','Robert Williams III','Re-signing','Returns on a 3-year deal'],
  ['Portland Trail Blazers','por','Branden Carlson','Signing','Signs a 1-year deal'],
  ['Portland Trail Blazers','por','Ja Morant','Trade','Acquired from Memphis'],
  ['Portland Trail Blazers','por','Micah Potter','Other','Claimed via waivers'],
  ['Portland Trail Blazers','por','Jeremy Sochan','Signing','Signs a 1-year deal'],
  ['Sacramento Kings','sac','Precious Achiuwa','Re-signing','Returns on a 2-year deal'],
  ['Sacramento Kings','sac','Daeqwon Plowden','Re-signing','Returns on a 2-year deal'],
  ['Sacramento Kings','sac','Ben Simmons','Signing','Signs a 1-year deal'],
  ['San Antonio Spurs','sas','Harrison Barnes','Re-signing','Returns on a 1-year deal'],
  ['San Antonio Spurs','sas','Julian Champagnie','Re-signing','Returns on a 3-year deal'],
  ['San Antonio Spurs','sas','Jordan McLaughlin','Re-signing','Returns on a 1-year deal'],
  ['San Antonio Spurs','sas','Victor Wembanyama','Re-signing','Signs a 5-year extension'],
  ['San Antonio Spurs','sas','Tobias Harris','Signing','Signs a 2-year deal'],
  ['Toronto Raptors','tor','Alijah Martin','Re-signing','Returns on a 2-year deal'],
  ['Toronto Raptors','tor','Kyle Anderson','Signing','Signs a 1-year deal'],
  ['Toronto Raptors','tor','Kawhi Leonard','Trade','Acquired from the Clippers'],
  ['Utah Jazz','uta','Mo Bamba','Re-signing','Returns on a 2-year deal'],
  ['Utah Jazz','uta','Jusuf Nurkić','Re-signing','Returns on a 2-year deal'],
  ['Utah Jazz','uta','Josh Green','Trade','Acquired from Minnesota'],
  ['Utah Jazz','uta','Jaxson Hayes','Signing','Signs a 2-year deal'],
  ['Utah Jazz','uta','Josh Okogie','Signing','Signs a 2-year deal'],
  ['Washington Wizards','was','Anthony Gill','Re-signing','Returns on a 1-year deal'],
  ['Washington Wizards','was','Trae Young','Re-signing','Returns on a 4-year deal'],
  ['Washington Wizards','was','Deandre Ayton','Trade','Acquired from the Lakers'],
  ['Washington Wizards','was','Tre Mann','Trade','Acquired from Charlotte in a 5-team deal'],
  ['Washington Wizards','was','Khris Middleton','Trade','Acquired from Dallas in a sign-and-trade']
];

const offseasonDepartures = [
  ['Atlanta Hawks','atl','Jonathan Kuminga','Departure','Left in free agency for Minnesota'],
  ['Atlanta Hawks','atl','Zaccharie Risacher','Departure','Traded to Dallas'],
  ['Boston Celtics','bos','Jaylen Brown','Departure','Traded to Philadelphia'],
  ['Boston Celtics','bos','Nikola Vučević','Departure','Left in free agency for Orlando'],
  ['Brooklyn Nets','bkn','Nic Claxton','Departure','Traded to Chicago in a 4-team deal'],
  ['Brooklyn Nets','bkn','Ziaire Williams','Departure','Left in free agency for the Lakers'],
  ['Charlotte Hornets','cha','LaMelo Ball','Departure','Traded to Minnesota in a 4-team deal'],
  ['Charlotte Hornets','cha','Miles Bridges','Departure','Traded to Phoenix'],
  ['Charlotte Hornets','cha','Josh Green','Departure','Traded to Minnesota in a 4-team deal'],
  ['Charlotte Hornets','cha','Tre Mann','Departure','Traded to Washington in a 5-team deal'],
  ['Chicago Bulls','chi','Mouhamed Gueye','Departure','Traded to Charlotte in a 4-team deal'],
  ['Chicago Bulls','chi','Nick Richards','Departure','Left in free agency for Miami'],
  ['Chicago Bulls','chi','Collin Sexton','Departure','Left in free agency for the Lakers'],
  ['Chicago Bulls','chi','Anfernee Simons','Departure','Left in free agency for Philadelphia'],
  ['Cleveland Cavaliers','cle','Keon Ellis','Departure','Left in free agency for Brooklyn'],
  ['Cleveland Cavaliers','cle','Larry Nance Jr.','Departure','Left in free agency for Indiana'],
  ['Cleveland Cavaliers','cle','Georges Niang','Departure','Left in free agency for Golden State'],
  ['Cleveland Cavaliers','cle','Dennis Schröder','Departure','Traded to Charlotte in a 5-team deal'],
  ['Cleveland Cavaliers','cle','Max Strus','Departure','Traded to the Clippers in a 5-team deal'],
  ['Cleveland Cavaliers','cle','Dean Wade','Departure','Left in free agency for Philadelphia'],
  ['Dallas Mavericks','dal','Marvin Bagley III','Departure','Left in free agency for Denver'],
  ['Dallas Mavericks','dal','AJ Johnson','Departure','Moved in the 6-team trade framework'],
  ['Dallas Mavericks','dal','Khris Middleton','Departure','Sign-and-traded to Washington'],
  ['Dallas Mavericks','dal','Ryan Nembhard','Departure','Traded to Atlanta'],
  ['Dallas Mavericks','dal','Klay Thompson','Departure','Left in free agency for Miami'],
  ['Dallas Mavericks','dal','Brandon Williams','Departure','Left in free agency for Golden State'],
  ['Denver Nuggets','den','Tim Hardaway Jr.','Departure','Left in free agency for Miami'],
  ['Denver Nuggets','den','Peyton Watson','Departure','Sign-and-traded to Cleveland'],
  ['Detroit Pistons','det','Tobias Harris','Departure','Left in free agency for San Antonio'],
  ['Detroit Pistons','det','Caris LeVert','Departure','Traded to Milwaukee'],
  ['Detroit Pistons','det','Marcus Sasser','Departure','Traded to Dallas'],
  ['Detroit Pistons','det','Isaiah Stewart','Departure','Traded to Memphis'],
  ['Golden State Warriors','gsw','Quinten Post','Departure','Left in free agency for Memphis'],
  ['Houston Rockets','hou','Dorian Finney-Smith','Departure','Traded to Charlotte'],
  ['Houston Rockets','hou','Josh Okogie','Departure','Left in free agency for Utah'],
  ['Indiana Pacers','ind','Kam Jones','Departure','Traded to Chicago on draft night'],
  ['Indiana Pacers','ind','Micah Potter','Departure','Claimed off waivers by Portland'],
  ['LA Clippers','lac','Bogdan Bogdanović','Departure','Left in free agency for Houston'],
  ['LA Clippers','lac','John Collins','Departure','Sign-and-traded to Detroit'],
  ['LA Clippers','lac','Kawhi Leonard','Departure','Traded to Toronto'],
  ['LA Clippers','lac','Bennedict Mathurin','Departure','Left in free agency for New Orleans'],
  ['Los Angeles Lakers','lal','Deandre Ayton','Departure','Traded to Washington'],
  ['Los Angeles Lakers','lal','Rui Hachimura','Departure','Left in free agency for the Clippers'],
  ['Los Angeles Lakers','lal','Jaxson Hayes','Departure','Left in free agency for Utah'],
  ['Los Angeles Lakers','lal','LeBron James','Departure','Left in free agency for Philadelphia'],
  ['Los Angeles Lakers','lal','Luke Kennard','Departure','Left in free agency for Phoenix'],
  ['Los Angeles Lakers','lal','Marcus Smart','Departure','Left in free agency for Houston'],
  ['Memphis Grizzlies','mem','Santi Aldama','Departure','Traded to Dallas'],
  ['Memphis Grizzlies','mem','Kentavious Caldwell-Pope','Departure','Bought out before signing with Philadelphia'],
  ['Memphis Grizzlies','mem','Taj Gibson','Departure','Traded to New Orleans'],
  ['Memphis Grizzlies','mem','Ja Morant','Departure','Traded to Portland'],
  ['Miami Heat','mia','Tyler Herro','Departure','Traded to Milwaukee in the Giannis deal'],
  ['Miami Heat','mia','Kasparas Jakučionis','Departure','Traded to Milwaukee in the Giannis deal'],
  ['Miami Heat','mia','Jaime Jaquez Jr.','Departure','Traded to Milwaukee in the Giannis deal'],
  ['Miami Heat','mia','Kel’el Ware','Departure','Traded to Milwaukee in the Giannis deal'],
  ['Miami Heat','mia','Norman Powell','Departure','Left in free agency for Chicago'],
  ['Milwaukee Bucks','mil','Giannis Antetokounmpo','Departure','Traded to Miami'],
  ['Milwaukee Bucks','mil','Bobby Portis','Departure','Traded to Miami'],
  ['Milwaukee Bucks','mil','Gary Harris','Departure','Traded to Detroit'],
  ['Milwaukee Bucks','mil','Taurean Prince','Departure','Traded to Detroit'],
  ['Minnesota Timberwolves','min','Kyle Anderson','Departure','Left in free agency for Toronto'],
  ['Minnesota Timberwolves','min','Mike Conley','Departure','Left in free agency for Boston'],
  ['Minnesota Timberwolves','min','John Konchar','Departure','Moved via waivers after the Utah trade'],
  ['Minnesota Timberwolves','min','Julius Randle','Departure','Traded to Brooklyn in a 4-team deal'],
  ['Minnesota Timberwolves','min','Naz Reid','Departure','Traded to Charlotte in a 4-team deal'],
  ['New Orleans Pelicans','nop','Jordan Hawkins','Departure','Traded to Memphis'],
  ['New Orleans Pelicans','nop','Kevon Looney','Departure','Left in free agency for the Lakers'],
  ['New Orleans Pelicans','nop','Micah Peavy','Departure','Traded to Memphis'],
  ['New York Knicks','nyk','Ariel Hukporti','Departure','Left in free agency for Philadelphia'],
  ['New York Knicks','nyk','Mitchell Robinson','Departure','Left in free agency for Boston'],
  ['New York Knicks','nyk','Jeremy Sochan','Departure','Left in free agency for Portland'],
  ['Oklahoma City Thunder','okc','Branden Carlson','Departure','Left in free agency for Portland'],
  ['Oklahoma City Thunder','okc','Luguentz Dort','Departure','Traded to Atlanta'],
  ['Oklahoma City Thunder','okc','Isaiah Joe','Departure','Traded to Detroit'],
  ['Oklahoma City Thunder','okc','Aaron Wiggins','Departure','Traded to Atlanta'],
  ['Orlando Magic','orl','Moritz Wagner','Departure','Left in free agency for Brooklyn'],
  ['Philadelphia 76ers','phi','Johni Broome','Departure','Traded to the Clippers'],
  ['Philadelphia 76ers','phi','Andre Drummond','Departure','Left in free agency for New York'],
  ['Philadelphia 76ers','phi','Paul George','Departure','Traded to Boston'],
  ['Philadelphia 76ers','phi','Quentin Grimes','Departure','Left in free agency for the Lakers'],
  ['Philadelphia 76ers','phi','Kelly Oubre Jr.','Departure','Left in free agency for Indiana'],
  ['Philadelphia 76ers','phi','Dalen Terry','Departure','Waived by Philadelphia'],
  ['Philadelphia 76ers','phi','Trendon Watford','Departure','Left in free agency for New Orleans'],
  ['Phoenix Suns','phx','Grayson Allen','Departure','Traded to Charlotte'],
  ['Phoenix Suns','phx','Royce O’Neale','Departure','Traded to Charlotte'],
  ['Portland Trail Blazers','por','Jerami Grant','Departure','Traded to Memphis'],
  ['Portland Trail Blazers','por','Kris Murray','Departure','Traded to Memphis'],
  ['Portland Trail Blazers','por','Matisse Thybulle','Departure','Left in free agency for the Lakers'],
  ['Sacramento Kings','sac','Devin Carter','Departure','Traded to Atlanta'],
  ['Sacramento Kings','sac','DeMar DeRozan','Departure','Left in free agency for Denver'],
  ['Toronto Raptors','tor','Gradey Dick','Departure','Traded to the Clippers'],
  ['Toronto Raptors','tor','Brandon Ingram','Departure','Traded to the Clippers'],
  ['Toronto Raptors','tor','Sandro Mamukelashvili','Departure','Left in free agency for the Lakers'],
  ['Utah Jazz','uta','Walker Kessler','Departure','Sign-and-traded to the Lakers'],
  ['Utah Jazz','uta','John Konchar','Departure','Left in free agency for New York'],
  ['Utah Jazz','uta','Cody Williams','Departure','Traded to Minnesota'],
  ['Washington Wizards','was','Jaden Hardy','Departure','Traded to the Lakers'],
  ['Washington Wizards','was','D’Angelo Russell','Departure','Traded to Memphis'],
  ['Washington Wizards','was','Cam Whitmore','Departure','Traded to Cleveland in a 5-team deal']
];

offseasonMoves.push(...offseasonDepartures);

const transactionList = document.getElementById('transactionList');

if (transactionList) {
  const teamSelect = document.getElementById('transactionTeam');
  const typeSelect = document.getElementById('transactionType');
  const searchInput = document.getElementById('transactionSearch');
  const moreButton = document.getElementById('transactionMore');
  let expanded = false;

  [...new Map(offseasonMoves.map(move => [move[1], move[0]])).entries()]
    .sort((a, b) => a[1].localeCompare(b[1]))
    .forEach(([abbr, team]) => teamSelect.add(new Option(`${team} · ${abbr.toUpperCase()}`, abbr)));

  const moveCounts = type => offseasonMoves.filter(move => move[3] === type).length;
  document.getElementById('transactionSummary').innerHTML = `
    <div><b>${offseasonMoves.length}</b><span>official team entries</span></div>
    <div><b>${moveCounts('Trade')}</b><span>trade arrivals</span></div>
    <div><b>${moveCounts('Signing')}</b><span>free-agent signings</span></div>
    <div><b>${moveCounts('Re-signing')}</b><span>re-signings + extensions</span></div>
    <div><b>${moveCounts('Departure')}</b><span>players who left</span></div>`;

  function renderTransactions() {
    const query = searchInput.value.trim().toLocaleLowerCase();
    const team = teamSelect.value;
    const type = typeSelect.value;
    const filtered = offseasonMoves.filter(move =>
      (team === 'all' || move[1] === team) &&
      (type === 'all' || move[3] === type) &&
      (!query || `${move[0]} ${move[2]} ${move[4]}`.toLocaleLowerCase().includes(query))
    );
    const visible = expanded ? filtered : filtered.slice(0, 24);
    transactionList.innerHTML = visible.length ? visible.map(move => `
      <article class="transaction-row">
        <a class="transaction-team" href="team.html?team=${encodeURIComponent(move[0])}"><img loading="lazy" src="https://a.espncdn.com/i/teamlogos/nba/500/${move[1]}.png" alt="${move[0]} logo"><span>${move[1].toUpperCase()}</span></a>
        <a class="transaction-player" href="player.html?player=${encodeURIComponent(move[2])}"><b>${move[2]}</b><small>${move[0]}</small></a>
        <span class="transaction-kind kind-${move[3].toLowerCase().replace(/[^a-z]+/g, '-')}">${move[3]}</span>
        <p>${move[4]}</p><a class="transaction-open" href="player.html?player=${encodeURIComponent(move[2])}" aria-label="Open ${move[2]} profile">→</a>
      </article>`).join('') : '<div class="transaction-empty"><b>No moves match those filters.</b><span>Try another team, type, or player search.</span></div>';
    document.getElementById('transactionCount').textContent = `Showing ${Math.min(visible.length, filtered.length)} of ${filtered.length} matching moves · ${new Set(filtered.map(move => move[1])).size} teams`;
    moreButton.hidden = filtered.length <= 24;
    moreButton.textContent = expanded ? 'SHOW FEWER ↑' : `SHOW ALL ${filtered.length} MOVES ↓`;
  }

  searchInput.addEventListener('input', () => { expanded = false; renderTransactions(); });
  teamSelect.addEventListener('change', () => { expanded = false; renderTransactions(); });
  typeSelect.addEventListener('change', () => { expanded = false; renderTransactions(); });
  moreButton.addEventListener('click', () => { expanded = !expanded; renderTransactions(); if (!expanded) document.getElementById('offseasonTrackerTitle').scrollIntoView({behavior:'smooth'}); });
  renderTransactions();
}
